#!/usr/bin/env bash

# One-time system setup for kawasaki.
# Fixes power management issues.

# ensure root user
if [ $EUID -ne 0 ]; then
    echo -e "\e[1m\e[31mYou must be root to run this script\e[0m"
    exit 1
fi

# ensure correct host
if [ $(hostname) != "kawasaki" ]; then
    echo -e "\e[1m\e[31mThis script is only for the host: kawasaki\e[0m"
    exit 1
fi

# determine the invoking (non-root) user’s home directory
USER_HOME=$(eval echo ~${SUDO_USER:-$USER})

# copy the fix scripts
cp -v "$USER_HOME/.bin/kawasaki/systemd/network_hack_hibernation" /usr/lib/systemd/system-sleep/
cp -v "$USER_HOME/.bin/kawasaki/systemd/lid_wakeup_disable"       /usr/lib/systemd/system-sleep/

echo -e "\e[1m\e[32mFixes successfully installed\e[0m"
