#!/usr/bin/env bash

# This program reconnects the the network module to the kernel.
# It is useful for reconnecting to wifi.

# ensure root user
if [[ $EUID -ne 0 ]]; then
    echo -e "\e[1m\e[31mYou must be root to run this script\e[0m"
    exit 1
fi

modprobe -r brcmfmac
modprobe brcmfmac

nmcli device status
