#!/usr/bin/env bash

# enable/disable laptop keyboard
$HOME/.config/i3/scripts/laptopkb

# monitor configuration and wallpapers
$HOME/.config/i3/scripts/setdisplay

# launch polybar
$HOME/.config/polybar/launch.sh
